import "./globals.css";
import LayoutWrapper from "@/Components/LayoutWrapper";
import '../Styles/login.css'
import '../Styles/profile.css'

export const metadata = {
  title: "Gradus",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
      <body>
        <LayoutWrapper>{children}</LayoutWrapper> {/* Wrap content in client logic */}
      </body>
    </html>
  );
}
